var res = {
    LoginUI_json : "res/ui/LoginUI.json",
    BroadcastUI_json : "res/ui/BroadcastUI.json",
    effect_lockui_png : "res/effect/effect_lockui.png",
    effect_lockui_plist : "res/effect/effect_lockui.plist",
    LockUI_json : "res/ui/LockUI.json",
    gameroom_bg_png : "res/ui/BackGround/gameroom_bg.png",
    gameroom_bg_desc_png : "res/ui/BackGround/bg_desc.png",
    card_png : "res/ui/card.png",
    card_plist : "res/ui/card.plist",
    biaoqing_png : "res/effect/biaoqing.png",
    biaoqing_plist : "res/effect/biaoqing.plist",
    common_talk_bg_png : "res/ui/Default/common_talk_bg.png",
    huaban_plist : "res/particles/huaban.plist",
    huaban_png : "res/particles/huaban.png",
    TurnCard_plist: "res/effect/TurnCard.plist",
    TurnCard_png : "res/effect/TurnCard.png",
    action_spring0_png : "res/effect/action_spring0.png",
    action_spring0_plist : "res/effect/action_spring0.plist",
    action_bomb0_plist: "res/effect/action_bomb0.plist",
    action_bomb0_png : "res/effect/action_bomb0.png",
    action_dbLine0_plist: "res/effect/action_dbLine0.plist",
    action_dbLine0_png : "res/effect/action_dbLine0.png",
    action_plane0_plist: "res/effect/action_plane0.plist",
    action_plane0_png : "res/effect/action_plane0.png",
    CardType0_plist: "res/effect/CardType0.plist",
    CardType0_png : "res/effect/CardType0.png",
    action_rocket0_plist: "res/effect/action_rocket0.plist",
    action_rocket0_png : "res/effect/action_rocket0.png",
    shunzi_plist: "res/effect/shunzi.plist",
    shunzi_png : "res/effect/shunzi.png",
    gamebg_png_1: "res/ui/GameRoomInfoUI/bg_img_1.png",
    gamebg_png_2: "res/ui/GameRoomInfoUI/bg_img_2.png",
    gamebg_png_3:  "res/ui/GameRoomInfoUI/bg_img_3.png",
    gamebg_label_png_1: "res/ui/GameRoomInfoUI/bg_label_img_1.png",
    gamebg_label_png_2: "res/ui/GameRoomInfoUI/bg_label_img_2.png",
    gamebg_label_png_3:  "res/ui/GameRoomInfoUI/bg_label_img_3.png",
    fireworks_png:  "res/effect/fireworks.png",
    fireworks_plist:  "res/effect/fireworks.plist",
    Trophy_png:  "res/effect/Trophy.png",
    Trophy_plist:  "res/effect/Trophy.plist",
    TrophyUI_png:  "res/effect/TrophyUI.png",
    TrophyUI_plist:  "res/effect/TrophyUI.plist",
    effectcard_png:  "res/effect/effectcard.png",
    effectcard_plist:  "res/effect/effectcard.plist",
    effectbtn_png:  "res/effect/effectbtn.png",
    effectbtn_plist:  "res/effect/effectbtn.plist",
    effectdice_png:  "res/effect/effectdice.png",
    effectdice_plist:  "res/effect/effectdice.plist",
    effectfireworks_png:  "res/effect/EffectFireworksUI.png",
    effectfireworks_plist:  "res/effect/EffectFireworksUI.plist",
    effectonlyone_png:  "res/effect/onlyone.png",
    effectonlyone_plist:  "res/effect/onlyone.plist",
    magicslipper_png:  "res/effect/MagicSlipperUI.png",
    magicslipper_plist:  "res/effect/MagicSlipperUI.plist",
    magickiss_png:  "res/effect/MagicKissUI.png",
    magickiss_plist:  "res/effect/MagicKissUI.plist",
    magicege_png:  "res/effect/MagicEgeUI.png",
    magicege_plist:  "res/effect/MagicEgeUI.plist",
    magiccheers_png:  "res/effect/MagicCheersUI.png",
    magiccheers_plist:  "res/effect/MagicCheersUI.plist",
    mascot_json: "res/effect/zhayan.json",
    mascot_atlas: "res/effect/zhayan.atlas",
    mascot_png:"res/effect/zhayan.png",
    mascot_1_plist: "res/effect/mascot.plist",
    mascot_1_json: "res/effect/mascot.ExportJson",
    mascot_1_png:"res/effect/mascot.png",
    union_bg_1:"res/ui/UnionHallUI/bg_hall_img_1.png",
    union_bg_2:"res/ui/UnionHallUI/bg_hall_img_2.png",
    union_bg_3:"res/ui/UnionHallUI/union_pop_img.png",
    communicate_bg_0:"res/ui/Default/common_talk_bg_0.png",
    communicate_bg_1:"res/ui/Default/common_talk_bg_1.png",
    communicate_bg_2:"res/ui/Default/common_talk_bg_2.png",
    sound_clock:"res/sound/effect/timeup_alarm.mp3",
    cattle_png:  "res/effect/cattle.png",
    cattle_plist:  "res/effect/cattle.plist",
    EffectStreamer_png:  "res/effect/EffectStreamerUI.png",
    EffectStreamerUI_plist:  "res/effect/EffectStreamerUI.plist",
    crown_png:  "res/effect/CrownUI.png",
    crown_plist:  "res/effect/CrownUI.plist",
    ad_point_0:"res/ui/GameHallUI/real_point.png",
    ad_point_1:"res/ui/GameHallUI/virtual_point.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
